name: release

on:
  push:
    branches:
      - main
  schedule:
    - cron: 23 13 * * 2
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        version: ["latest"]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: aaomidi/tailscale-sidecar:$${{ matrix.version }}
          build-args:
            - VERSION=${{ matrix.version }}
